### ISSUE TITLE
Unresolved references

### ISSUE THREAD

**Issue by dragokas** [OlimilO1402/Asm_Unsigned#2]
```
Module=MString; ..\Sys_Strings\Modules\MString.bas
Module=MPtr; ..\Ptr_Pointers\Modules\MPtr.bas
```
could not be found.

Please, add them explicitly or mention in your project where they could be added from.
Thank you.

Good job!

**Comment by OlimilO1402** [comment]
Hi dragokas, thanks for testing, maybe I should do this but I must confess I am not sure in this point. I guess you found it anyway, have you? If not, you posted the solution already. The path to every missing module is the name of the repo: for MString the name of the repo is Sys_Strings, for MPtr the name of the repo is Ptr_Pointers. I have described it already in my profile below "Some Infos about sourcode-structure". OK, Maybe not everybody reads this in the first place. I am on another way to address this problem. If you are interested have a look at Config_IniPrivateProfile. I "could" read the vbp, zip the files to one zip, and make all files available in the release zip. If I only had more time to do all the stuff. But you know . . . moreover If anybody tries to compile my stuff I always appreciate it tha someone gets into contact with me. As you did! So making it too easy for everybody is no benefit for *me* you get the idea!

**Comment by dragokas** [comment]
Yeah, thanks. I found it.
